- bplan/static/js/app/components/list/listitem.html
- bplan/static/js/app/components/map/popup.html
- bplan/static/js/app/shared/directives/nav.html
> change wording "bplan" to "bebauungs(-)plan"

- bplan/management/commands/load_bplan.py
> guarantee minimal distances between all bplan points

- bplan/filters.py
- bplan/management/commands/insert_addresses.py
> enable abbreviating "strasse" to "str" in addresses

- .gitignore
- bplan/static/js/app/shared/controllers/viewController.js
- bplan/static/js/app/shared/directives/nav.html
> show informative error if there's no house number

- bplan/static/js/app/components/map/mapControllers.js
> apply filter to polygons, not just points

- bplan/static/js/app/components/map/popup.html
> add bezirk_name to map list item

- bplan/static/js/app/components/map/mapControllers.js
> open leaflet in new tab

- bplan/management/commands/load_bplan.py
> the round must in the cornery

- bplan/static/js/app/shared/directives/nav.html
- bplan/static/scss/components/_checkbox.scss
- bplan/static/scss/components/_nav.scss
fixes #37.
One thing bothers me, though: if you check a checkbox in the dropdown, the dropdown closes automatically. I think this is suboptimal, but it's the bootstrap code.
> improve filter ui

- bplan/serializers.py
- bplan/static/js/app/shared/services/placeService.js
- bplan/templates/base.html
- bplan/views.py
go to http://localhost:8000/berlin/?afs_behoer=Senat to see just senat plans
> Mn 2017 03 add filter for bplans from senat

- bplan/management/commands/insert_addresses.py
- bplan/management/commands/insert_numberless_addresses.py
- bplan/management/commands/load_bezirke.py
- bplan/management/commands/load_bplan.py
- bplan/management/commands/load_ortsteile.py
> tqdm: don't show download bars if verbosity is 0, for cronjobs

- django_zbp/settings/production.py
- django_zbp/whitenoise.py
- requirements.txt
Equivalent to all other a4 projects.
> add whitenoise support and enable it

- Makefile
- bplan/static/scss/all.compiled.css
- bplan/templates/admin_base.html
- bplan/templates/base.html
- django_zbp/settings/base.py
- django_zbp/settings/production.py
- django_zbp/whitenoise.py
- requirements-dev.txt
- requirements.txt
In the end I did not manage to use webpack and present you this wonderful workaround.
We have the scss file "compiled" in the repo and a make command to regenerate him.
I am happy about easy and concrete other options, but unfortunately webpack and me could not became friends.
The whitenoise code is from @treba123
> Remove django compressor and use whitenoise

- bplan/assets/js/app/components/list/listitem.html
- bplan/assets/js/app/components/list/listitemmobile.html
- bplan/assets/js/app/components/map/popup.html
- bplan/static/js/app/components/list/listitem.html
- bplan/static/js/app/components/list/listitemmobile.html
- bplan/static/js/app/components/map/popup.html
I'm not sure why the files are in there twice?
> #1903 wording change BPlanScan: changed wording on list item link btn

- bplan/assets/scss/all.scss
- bplan/assets/scss/core/_bootstrap-variables.scss
I cannot reproduce issue locally so this was kind of a guess at what might be wrong, not sure how to go about this stuff when I can't test?
> fonts: hopefully will fix font loading problem

- package.json
- webpack.config.js
fixes https://github.com/liqd/django_zbp/issues/90
> webpack: Add leaflet webpack compatibility addon

- webpack.prod.js
> webpack: Update merge import

- bplan/management/commands/load_bplan.py
Unluckily we missed the sentence about the changed features. Luckily, the ones that are gone are not really needed. We should also delete them from the model, once this works.
Still to do:
> adapt load command script to new schema, delete unused features

- bplan/assets/html/app/components/map/popup.html
- bplan/assets/html/app/shared/directives/nav.html
- bplan/templates/downloads.html
- package.json
- webpack.common.js
The problem wasn't actually font awesome, but the file-loader in webpack.common. 
Now the icon in the popup is not on the right side anymore locally, which does not make sense. I think, I will try on stage.
> deps: update fontaweseome

- bplan/assets/html/app/components/map/popup.html
- bplan/assets/html/app/shared/directives/nav.html
- bplan/templates/admin_base.html
- bplan/templates/base.html
> fix pull-right rename

- bplan/assets/js/app/components/map/mapControllers.js
- bplan/templates/base.html
- bplan/views.py
- django_zbp/settings/base.py
> load map url from django settings

- bplan/views.py
> don't cache main views

- Makefile
- changelog/_1111.md
- requirements-dev.txt
- requirements.txt
remove old unused dependencies
> remove unused dependencies
